// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_UserInputTextArea = NULL;
lv_obj_t * ui_PasswordInputTextArea = NULL;
lv_obj_t * ui_LoginButton = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_RegisterButton = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_Image30 = NULL;
lv_obj_t * ui_Image35 = NULL;
lv_obj_t * ui_Image36 = NULL;
lv_obj_t * ui_Image37 = NULL;
lv_obj_t * ui_Image38 = NULL;
lv_obj_t * ui_Label13 = NULL;
// event funtions
void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_UserInputTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_UserInputTextArea);
    }
}

void ui_event_PasswordInputTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_PasswordInputTextArea);
    }
}

void ui_event_LoginButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LogIn(e);
    }
}

void ui_event_RegisterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Register(e);
    }
}

void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SelectProfilePhoto(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_692897373);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 450
    lv_obj_set_x(ui_Image1, 7);
    lv_obj_set_y(ui_Image1, 5);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 280);

    ui_UserInputTextArea = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_UserInputTextArea, 321);
    lv_obj_set_height(ui_UserInputTextArea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_UserInputTextArea, 38);
    lv_obj_set_y(ui_UserInputTextArea, -121);
    lv_obj_set_align(ui_UserInputTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_UserInputTextArea, 15);
    lv_textarea_set_placeholder_text(ui_UserInputTextArea, "用户名");
    lv_textarea_set_one_line(ui_UserInputTextArea, true);
    lv_obj_set_style_text_font(ui_UserInputTextArea, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordInputTextArea = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_PasswordInputTextArea, 322);
    lv_obj_set_height(ui_PasswordInputTextArea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_PasswordInputTextArea, 38);
    lv_obj_set_y(ui_PasswordInputTextArea, -35);
    lv_obj_set_align(ui_PasswordInputTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PasswordInputTextArea, 15);
    lv_textarea_set_placeholder_text(ui_PasswordInputTextArea, "密码");
    lv_textarea_set_one_line(ui_PasswordInputTextArea, true);
    lv_textarea_set_password_mode(ui_PasswordInputTextArea, true);
    lv_obj_set_style_text_font(ui_PasswordInputTextArea, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_LoginButton, 100);
    lv_obj_set_height(ui_LoginButton, 50);
    lv_obj_set_x(ui_LoginButton, -75);
    lv_obj_set_y(ui_LoginButton, 72);
    lv_obj_set_align(ui_LoginButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoginButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LoginButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_LoginButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "登录");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_RegisterButton, 100);
    lv_obj_set_height(ui_RegisterButton, 50);
    lv_obj_set_x(ui_RegisterButton, 145);
    lv_obj_set_y(ui_RegisterButton, 74);
    lv_obj_set_align(ui_RegisterButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RegisterButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RegisterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_RegisterButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "注册");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 543);
    lv_obj_set_height(ui_Keyboard1, 201);
    lv_obj_set_x(ui_Keyboard1, -2);
    lv_obj_set_y(ui_Keyboard1, 131);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_options(ui_Dropdown1,
                            "profile photo 1\nprofile photo 2\nprofile photo 3\nprofile photo 4\nprofile photo 5");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -238);
    lv_obj_set_y(ui_Dropdown1, -8);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Image30 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image30, &ui_img_funina_png);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 282
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 282
    lv_obj_set_x(ui_Image30, -240);
    lv_obj_set_y(ui_Image30, -116);
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image30, 100);

    ui_Image35 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image35, &ui_img_keqing_png);
    lv_obj_set_width(ui_Image35, LV_SIZE_CONTENT);   /// 282
    lv_obj_set_height(ui_Image35, LV_SIZE_CONTENT);    /// 282
    lv_obj_set_x(ui_Image35, -242);
    lv_obj_set_y(ui_Image35, -128);
    lv_obj_set_align(ui_Image35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image35, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image35, 100);

    ui_Image36 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image36, &ui_img_linnite_png);
    lv_obj_set_width(ui_Image36, LV_SIZE_CONTENT);   /// 282
    lv_obj_set_height(ui_Image36, LV_SIZE_CONTENT);    /// 282
    lv_obj_set_x(ui_Image36, -241);
    lv_obj_set_y(ui_Image36, -129);
    lv_obj_set_align(ui_Image36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image36, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image36, 100);

    ui_Image37 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image37, &ui_img_paimen_png);
    lv_obj_set_width(ui_Image37, LV_SIZE_CONTENT);   /// 282
    lv_obj_set_height(ui_Image37, LV_SIZE_CONTENT);    /// 282
    lv_obj_set_x(ui_Image37, -237);
    lv_obj_set_y(ui_Image37, -128);
    lv_obj_set_align(ui_Image37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image37, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image37, 100);

    ui_Image38 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image38, &ui_img_qiqi_png);
    lv_obj_set_width(ui_Image38, LV_SIZE_CONTENT);   /// 282
    lv_obj_set_height(ui_Image38, LV_SIZE_CONTENT);    /// 282
    lv_obj_set_x(ui_Image38, -240);
    lv_obj_set_y(ui_Image38, -131);
    lv_obj_set_align(ui_Image38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image38, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image38, 100);

    ui_Label13 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 34);
    lv_obj_set_y(ui_Label13, -81);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "\n      登陆失败      \n");
    lv_obj_add_flag(ui_Label13, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Label13, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label13, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label13, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserInputTextArea, ui_event_UserInputTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordInputTextArea, ui_event_PasswordInputTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoginButton, ui_event_LoginButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RegisterButton, ui_event_RegisterButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_UserInputTextArea);
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    ui_UserInputTextArea = NULL;
    ui_PasswordInputTextArea = NULL;
    ui_LoginButton = NULL;
    ui_Label2 = NULL;
    ui_RegisterButton = NULL;
    ui_Label1 = NULL;
    ui_Keyboard1 = NULL;
    ui_Dropdown1 = NULL;
    ui_Image30 = NULL;
    ui_Image35 = NULL;
    ui_Image36 = NULL;
    ui_Image37 = NULL;
    ui_Image38 = NULL;
    ui_Label13 = NULL;

}
