// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image40 = NULL;
lv_obj_t * ui_Image53 = NULL;
// event funtions
void ui_event_Image2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Image28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Image14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_Image40(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Image53(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image3, &ui_img_1765838170);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 566
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image2, &ui_img_cloudy_sunny_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 415
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 415
    lv_obj_set_x(ui_Image2, -167);
    lv_obj_set_y(ui_Image2, -97);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 170);

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -168);
    lv_obj_set_y(ui_Label3, -32);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "天气");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 119);
    lv_obj_set_y(ui_Label8, -20);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "开关灯");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -170);
    lv_obj_set_y(ui_Label9, 180);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "聊天");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 117);
    lv_obj_set_y(ui_Label10, 176);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "游戏");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image28 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image28, &ui_img_517448795);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 1024
    lv_obj_set_x(ui_Image28, 109);
    lv_obj_set_y(ui_Image28, -125);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image28, 36);

    ui_Image14 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image14, &ui_img_1501167182);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1024
    lv_obj_set_x(ui_Image14, 116);
    lv_obj_set_y(ui_Image14, 82);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image14, 36);

    ui_Image40 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image40, &ui_img_chat_png);
    lv_obj_set_width(ui_Image40, LV_SIZE_CONTENT);   /// 168
    lv_obj_set_height(ui_Image40, LV_SIZE_CONTENT);    /// 168
    lv_obj_set_x(ui_Image40, -171);
    lv_obj_set_y(ui_Image40, 82);
    lv_obj_set_align(ui_Image40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image40, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image40, 210);

    ui_Image53 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image53, &ui_img_1609717271);
    lv_obj_set_width(ui_Image53, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image53, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image53, -363);
    lv_obj_set_y(ui_Image53, -208);
    lv_obj_set_align(ui_Image53, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image53, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image53, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image28, ui_event_Image28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image14, ui_event_Image14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image40, ui_event_Image40, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image53, ui_event_Image53, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image3 = NULL;
    ui_Image2 = NULL;
    ui_Label3 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Image28 = NULL;
    ui_Image14 = NULL;
    ui_Image40 = NULL;
    ui_Image53 = NULL;

}
