// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_ImageSunny = NULL;
lv_obj_t * ui_ImagePartlyCloudy = NULL;
lv_obj_t * ui_ImageCloudy = NULL;
lv_obj_t * ui_ImageMidrain = NULL;
lv_obj_t * ui_ImageHeavyrain = NULL;
lv_obj_t * ui_ImageThundershower = NULL;
lv_obj_t * ui_ImageSleet = NULL;
lv_obj_t * ui_ImageLightSnow = NULL;
lv_obj_t * ui_ImageLightrain = NULL;
lv_obj_t * ui_ImageMidsnow = NULL;
lv_obj_t * ui_ImageHeavysnow = NULL;
lv_obj_t * ui_LabelWeatertoday = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_LabelWeaterfuther = NULL;
lv_obj_t * ui_Image54 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Dropdown3 = NULL;
lv_obj_t * ui_ImageMai = NULL;
lv_obj_t * ui_ImageWu = NULL;
// event funtions
void ui_event_Image54(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ConfirmCheck(e);
    }
}

void ui_event_Dropdown3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        CheckWeather(e);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image4, &ui_img_1528267563);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1000
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 561
    lv_obj_set_x(ui_Image4, 60);
    lv_obj_set_y(ui_Image4, 19);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 237);

    ui_ImageSunny = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageSunny, &ui_img_frame_27_png);
    lv_obj_set_width(ui_ImageSunny, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageSunny, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageSunny, -265);
    lv_obj_set_y(ui_ImageSunny, -124);
    lv_obj_set_align(ui_ImageSunny, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSunny, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSunny, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImagePartlyCloudy = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImagePartlyCloudy, &ui_img_1298383682);
    lv_obj_set_width(ui_ImagePartlyCloudy, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImagePartlyCloudy, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImagePartlyCloudy, -280);
    lv_obj_set_y(ui_ImagePartlyCloudy, -127);
    lv_obj_set_align(ui_ImagePartlyCloudy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePartlyCloudy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePartlyCloudy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCloudy = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageCloudy, &ui_img_frame_31_png);
    lv_obj_set_width(ui_ImageCloudy, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageCloudy, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageCloudy, -269);
    lv_obj_set_y(ui_ImageCloudy, -132);
    lv_obj_set_align(ui_ImageCloudy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCloudy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCloudy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageMidrain = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageMidrain, &ui_img_frame_32_png);
    lv_obj_set_width(ui_ImageMidrain, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageMidrain, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageMidrain, -275);
    lv_obj_set_y(ui_ImageMidrain, -111);
    lv_obj_set_align(ui_ImageMidrain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMidrain, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMidrain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHeavyrain = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageHeavyrain, &ui_img_frame_33_png);
    lv_obj_set_width(ui_ImageHeavyrain, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageHeavyrain, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageHeavyrain, -269);
    lv_obj_set_y(ui_ImageHeavyrain, -113);
    lv_obj_set_align(ui_ImageHeavyrain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHeavyrain, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHeavyrain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageThundershower = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageThundershower, &ui_img_frame_35_png);
    lv_obj_set_width(ui_ImageThundershower, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageThundershower, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageThundershower, -263);
    lv_obj_set_y(ui_ImageThundershower, -109);
    lv_obj_set_align(ui_ImageThundershower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageThundershower, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageThundershower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSleet = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageSleet, &ui_img_frame_36_png);
    lv_obj_set_width(ui_ImageSleet, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageSleet, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageSleet, -266);
    lv_obj_set_y(ui_ImageSleet, -108);
    lv_obj_set_align(ui_ImageSleet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSleet, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSleet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLightSnow = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageLightSnow, &ui_img_frame_38_png);
    lv_obj_set_width(ui_ImageLightSnow, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageLightSnow, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageLightSnow, -262);
    lv_obj_set_y(ui_ImageLightSnow, -104);
    lv_obj_set_align(ui_ImageLightSnow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLightSnow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLightSnow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLightrain = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageLightrain, &ui_img_frame_40_png);
    lv_obj_set_width(ui_ImageLightrain, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageLightrain, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageLightrain, -268);
    lv_obj_set_y(ui_ImageLightrain, -107);
    lv_obj_set_align(ui_ImageLightrain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLightrain, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLightrain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageMidsnow = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageMidsnow, &ui_img_frame_41_png);
    lv_obj_set_width(ui_ImageMidsnow, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageMidsnow, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageMidsnow, -263);
    lv_obj_set_y(ui_ImageMidsnow, -110);
    lv_obj_set_align(ui_ImageMidsnow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMidsnow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMidsnow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHeavysnow = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageHeavysnow, &ui_img_frame_42_png);
    lv_obj_set_width(ui_ImageHeavysnow, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_ImageHeavysnow, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_ImageHeavysnow, -247);
    lv_obj_set_y(ui_ImageHeavysnow, -111);
    lv_obj_set_align(ui_ImageHeavysnow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHeavysnow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHeavysnow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeatertoday = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelWeatertoday, 320);
    lv_obj_set_height(ui_LabelWeatertoday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatertoday, -213);
    lv_obj_set_y(ui_LabelWeatertoday, 93);
    lv_obj_set_align(ui_LabelWeatertoday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeatertoday, "深圳市  \n晴朗 \n温度:13 \n湿度:64\n1级北风 \n空气质量优秀");
    lv_obj_set_style_text_font(ui_LabelWeatertoday, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 6);
    lv_obj_set_y(ui_Label12, -161);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "未来5天天气:");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeaterfuther = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelWeaterfuther, 486);
    lv_obj_set_height(ui_LabelWeaterfuther, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeaterfuther, 312);
    lv_obj_set_y(ui_LabelWeaterfuther, 110);
    lv_label_set_text(ui_LabelWeaterfuther,
                      "2025-12-27 温度12~20度 晴\n2025-12-27 温度12~20度 晴\n2025-12-27 温度12~20度 晴\n2025-12-27 温度12~20度 晴\n2025-12-27 温度12~20度 晴");
    lv_obj_set_style_text_font(ui_LabelWeaterfuther, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image54 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image54, &ui_img_1609717271);
    lv_obj_set_width(ui_Image54, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image54, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image54, -363);
    lv_obj_set_y(ui_Image54, -208);
    lv_obj_set_align(ui_Image54, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image54, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image54, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, 136);
    lv_obj_set_y(ui_Button7, 170);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 2);
    lv_obj_set_y(ui_Label11, 3);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "查询");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown3 = lv_dropdown_create(ui_Screen3);
    lv_dropdown_set_options(ui_Dropdown3,
                            "深圳\n北京\n上海\n广州\n哈尔滨\n乌鲁木齐\n齐齐哈尔\n呼和浩特");
    lv_obj_set_width(ui_Dropdown3, 118);
    lv_obj_set_height(ui_Dropdown3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown3, 8);
    lv_obj_set_y(ui_Dropdown3, 169);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown3, &ui_font_TextFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Dropdown3, &lv_font_montserrat_12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown3), &ui_font_TextFont16,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown3), &ui_font_TextFont16,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ImageMai = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageMai, &ui_img_1938478117);
    lv_obj_set_width(ui_ImageMai, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_ImageMai, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_ImageMai, -265);
    lv_obj_set_y(ui_ImageMai, -120);
    lv_obj_set_align(ui_ImageMai, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMai, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMai, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWu = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageWu, &ui_img_701658425);
    lv_obj_set_width(ui_ImageWu, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_ImageWu, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_ImageWu, -261);
    lv_obj_set_y(ui_ImageWu, -131);
    lv_obj_set_align(ui_ImageWu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWu, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image54, ui_event_Image54, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown3, ui_event_Dropdown3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Image4 = NULL;
    ui_ImageSunny = NULL;
    ui_ImagePartlyCloudy = NULL;
    ui_ImageCloudy = NULL;
    ui_ImageMidrain = NULL;
    ui_ImageHeavyrain = NULL;
    ui_ImageThundershower = NULL;
    ui_ImageSleet = NULL;
    ui_ImageLightSnow = NULL;
    ui_ImageLightrain = NULL;
    ui_ImageMidsnow = NULL;
    ui_ImageHeavysnow = NULL;
    ui_LabelWeatertoday = NULL;
    ui_Label12 = NULL;
    ui_LabelWeaterfuther = NULL;
    ui_Image54 = NULL;
    ui_Button7 = NULL;
    ui_Label11 = NULL;
    ui_Dropdown3 = NULL;
    ui_ImageMai = NULL;
    ui_ImageWu = NULL;

}
