// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_ImageSunny;
extern lv_obj_t * ui_ImagePartlyCloudy;
extern lv_obj_t * ui_ImageCloudy;
extern lv_obj_t * ui_ImageMidrain;
extern lv_obj_t * ui_ImageHeavyrain;
extern lv_obj_t * ui_ImageThundershower;
extern lv_obj_t * ui_ImageSleet;
extern lv_obj_t * ui_ImageLightSnow;
extern lv_obj_t * ui_ImageLightrain;
extern lv_obj_t * ui_ImageMidsnow;
extern lv_obj_t * ui_ImageHeavysnow;
extern lv_obj_t * ui_LabelWeatertoday;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_LabelWeaterfuther;
extern void ui_event_Image54(lv_event_t * e);
extern lv_obj_t * ui_Image54;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label11;
extern void ui_event_Dropdown3(lv_event_t * e);
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_ImageMai;
extern lv_obj_t * ui_ImageWu;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

