// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label20;
extern void ui_event_Image29(lv_event_t * e);
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_Label15;
extern void ui_event_Image31(lv_event_t * e);
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Label16;
extern void ui_event_Image32(lv_event_t * e);
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Label17;
extern void ui_event_Image33(lv_event_t * e);
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Label18;
extern void ui_event_Image34(lv_event_t * e);
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Label19;
extern void ui_event_TextArea8(lv_event_t * e);
extern lv_obj_t * ui_TextArea8;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label14;
extern void ui_event_Panel10(lv_event_t * e);
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image41;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image52;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_TextArea1;
extern void ui_event_Image56(lv_event_t * e);
extern lv_obj_t * ui_Image56;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

