// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern void ui_event_UserInputTextArea(lv_event_t * e);
extern lv_obj_t * ui_UserInputTextArea;
extern void ui_event_PasswordInputTextArea(lv_event_t * e);
extern lv_obj_t * ui_PasswordInputTextArea;
extern void ui_event_LoginButton(lv_event_t * e);
extern lv_obj_t * ui_LoginButton;
extern lv_obj_t * ui_Label2;
extern void ui_event_RegisterButton(lv_event_t * e);
extern lv_obj_t * ui_RegisterButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_Image36;
extern lv_obj_t * ui_Image37;
extern lv_obj_t * ui_Image38;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

