// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Image39 = NULL;
lv_obj_t * ui_Image42 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Image43 = NULL;
lv_obj_t * ui_Image44 = NULL;
lv_obj_t * ui_Image45 = NULL;
lv_obj_t * ui_Image46 = NULL;
lv_obj_t * ui_Image47 = NULL;
lv_obj_t * ui_Image48 = NULL;
lv_obj_t * ui_Image49 = NULL;
lv_obj_t * ui_Image50 = NULL;
lv_obj_t * ui_Image51 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Image57 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GameStart(e);
    }
}

void ui_event_Image57(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0xBBAF6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image16, &ui_img_998060503);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image16, -273);
    lv_obj_set_y(ui_Image16, -31);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image39 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image39, &ui_img_998060503);
    lv_obj_set_width(ui_Image39, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image39, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image39, 278);
    lv_obj_set_y(ui_Image39, -22);
    lv_obj_set_align(ui_Image39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image39, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image42 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image42, &ui_img_1343904826);
    lv_obj_set_width(ui_Image42, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_Image42, LV_SIZE_CONTENT);    /// 160
    lv_obj_set_x(ui_Image42, -6);
    lv_obj_set_y(ui_Image42, -12);
    lv_obj_set_align(ui_Image42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image42, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image42, 400);

    ui_Button2 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -11);
    lv_obj_set_y(ui_Button2, 183);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -1);
    lv_obj_set_y(ui_Label24, 1);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "匹配");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -283);
    lv_obj_set_y(ui_Label25, 104);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "玩家1");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 275);
    lv_obj_set_y(ui_Label26, 111);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "玩家2");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -4);
    lv_obj_set_y(ui_Label28, -170);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "现在是玩家1的回合");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image43 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image43, &ui_img_ok_png);
    lv_obj_set_width(ui_Image43, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image43, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image43, -70);
    lv_obj_set_y(ui_Image43, -74);
    lv_obj_set_align(ui_Image43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image43, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image44 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image44, &ui_img_x_png);
    lv_obj_set_width(ui_Image44, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image44, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image44, -5);
    lv_obj_set_y(ui_Image44, -73);
    lv_obj_set_align(ui_Image44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image44, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image45 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image45, &ui_img_x_png);
    lv_obj_set_width(ui_Image45, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image45, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image45, 58);
    lv_obj_set_y(ui_Image45, -73);
    lv_obj_set_align(ui_Image45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image45, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image46 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image46, &ui_img_ok_png);
    lv_obj_set_width(ui_Image46, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image46, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image46, -4);
    lv_obj_set_y(ui_Image46, -11);
    lv_obj_set_align(ui_Image46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image46, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image47 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image47, &ui_img_ok_png);
    lv_obj_set_width(ui_Image47, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image47, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image47, 58);
    lv_obj_set_y(ui_Image47, 50);
    lv_obj_set_align(ui_Image47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image47, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image48 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image48, &ui_img_x_png);
    lv_obj_set_width(ui_Image48, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image48, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image48, 55);
    lv_obj_set_y(ui_Image48, -13);
    lv_obj_set_align(ui_Image48, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image48, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image49 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image49, &ui_img_x_png);
    lv_obj_set_width(ui_Image49, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image49, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image49, -68);
    lv_obj_set_y(ui_Image49, 48);
    lv_obj_set_align(ui_Image49, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image49, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image49, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image50 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image50, &ui_img_ok_png);
    lv_obj_set_width(ui_Image50, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image50, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image50, -5);
    lv_obj_set_y(ui_Image50, 50);
    lv_obj_set_align(ui_Image50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image50, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image51 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image51, &ui_img_x_png);
    lv_obj_set_width(ui_Image51, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image51, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image51, -69);
    lv_obj_set_y(ui_Image51, -13);
    lv_obj_set_align(ui_Image51, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image51, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image51, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 1);
    lv_obj_set_y(ui_Label27, 134);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "匹配中...");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image57 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image57, &ui_img_1609717271);
    lv_obj_set_width(ui_Image57, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image57, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image57, -363);
    lv_obj_set_y(ui_Image57, -207);
    lv_obj_set_align(ui_Image57, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image57, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image57, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image57, ui_event_Image57, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Image16 = NULL;
    ui_Image39 = NULL;
    ui_Image42 = NULL;
    ui_Button2 = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_Label26 = NULL;
    ui_Label28 = NULL;
    ui_Image43 = NULL;
    ui_Image44 = NULL;
    ui_Image45 = NULL;
    ui_Image46 = NULL;
    ui_Image47 = NULL;
    ui_Image48 = NULL;
    ui_Image49 = NULL;
    ui_Image50 = NULL;
    ui_Image51 = NULL;
    ui_Label27 = NULL;
    ui_Image57 = NULL;

}
