// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image39;
extern lv_obj_t * ui_Image42;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Image43;
extern lv_obj_t * ui_Image44;
extern lv_obj_t * ui_Image45;
extern lv_obj_t * ui_Image46;
extern lv_obj_t * ui_Image47;
extern lv_obj_t * ui_Image48;
extern lv_obj_t * ui_Image49;
extern lv_obj_t * ui_Image50;
extern lv_obj_t * ui_Image51;
extern lv_obj_t * ui_Label27;
extern void ui_event_Image57(lv_event_t * e);
extern lv_obj_t * ui_Image57;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

