// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_692897373);    // assets/wallhaven-gpv8wl_W_800px.png
LV_IMG_DECLARE(ui_img_funina_png);    // assets/funina.png
LV_IMG_DECLARE(ui_img_keqing_png);    // assets/keqing.png
LV_IMG_DECLARE(ui_img_linnite_png);    // assets/linnite.png
LV_IMG_DECLARE(ui_img_paimen_png);    // assets/paimen.png
LV_IMG_DECLARE(ui_img_qiqi_png);    // assets/qiqi.png
LV_IMG_DECLARE(ui_img_1765838170);    // assets/wallhaven-9dykpd_W_800px.png
LV_IMG_DECLARE(ui_img_cloudy_sunny_png);    // assets/Cloudy sunny.png
LV_IMG_DECLARE(ui_img_517448795);    // assets/灯泡打开(lightbulb on)_爱给网_aigei_com.png
LV_IMG_DECLARE(ui_img_1501167182);    // assets/游戏控制(games control)_爱给网_aigei_com.png
LV_IMG_DECLARE(ui_img_chat_png);    // assets/chat.png
LV_IMG_DECLARE(ui_img_1609717271);    // assets/返回.png
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_557891352);    // assets/02-灯泡.png
LV_IMG_DECLARE(ui_img_463845234);    // assets/02-灯泡 (1).png
LV_IMG_DECLARE(ui_img_1528267563);    // assets/生成天气预报背景图.png
LV_IMG_DECLARE(ui_img_frame_27_png);    // assets/Frame 27.png
LV_IMG_DECLARE(ui_img_1298383682);    // assets/Frame 28 (1).png
LV_IMG_DECLARE(ui_img_frame_31_png);    // assets/Frame 31.png
LV_IMG_DECLARE(ui_img_frame_32_png);    // assets/Frame 32.png
LV_IMG_DECLARE(ui_img_frame_33_png);    // assets/Frame 33.png
LV_IMG_DECLARE(ui_img_frame_35_png);    // assets/Frame 35.png
LV_IMG_DECLARE(ui_img_frame_36_png);    // assets/Frame 36.png
LV_IMG_DECLARE(ui_img_frame_38_png);    // assets/Frame 38.png
LV_IMG_DECLARE(ui_img_frame_40_png);    // assets/Frame 40.png
LV_IMG_DECLARE(ui_img_frame_41_png);    // assets/Frame 41.png
LV_IMG_DECLARE(ui_img_frame_42_png);    // assets/Frame 42.png
LV_IMG_DECLARE(ui_img_1938478117);    // assets/霾 (1).png
LV_IMG_DECLARE(ui_img_701658425);    // assets/雾.png
LV_IMG_DECLARE(ui_img_831548361);    // assets/人人人.png
LV_IMG_DECLARE(ui_img_keqing1_png);    // assets/keqing1.png
LV_IMG_DECLARE(ui_img_funina1_png);    // assets/funina1.png
LV_IMG_DECLARE(ui_img_paimen1_png);    // assets/paimen1.png
LV_IMG_DECLARE(ui_img_linnite1_png);    // assets/linnite1.png
LV_IMG_DECLARE(ui_img_qiqi1_png);    // assets/qiqi1.png
LV_IMG_DECLARE(ui_img_x_png);    // assets/x.png
LV_IMG_DECLARE(ui_img_funina2_png);    // assets/funina2.png
LV_IMG_DECLARE(ui_img_keqing2_png);    // assets/keqing2.png
LV_IMG_DECLARE(ui_img_linnite2_png);    // assets/linnite2.png
LV_IMG_DECLARE(ui_img_paimen2_png);    // assets/paimen2.png
LV_IMG_DECLARE(ui_img_qiqi2_png);    // assets/qiqi2.png
LV_IMG_DECLARE(ui_img_998060503);    // assets/玩游戏.png
LV_IMG_DECLARE(ui_img_1343904826);    // assets/井字棋盘_爱给网_aigei_com (1).png
LV_IMG_DECLARE(ui_img_ok_png);    // assets/ok.png

// FONTS
LV_FONT_DECLARE(ui_font_TextFont16);
LV_FONT_DECLARE(ui_font_TextFont32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
