// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "weather.h"

/*=====================登录界面回调函数===========================*/
void LogIn(lv_event_t * e)
{
	if(loginUser()) {
	}
}

void Register(lv_event_t * e)
{
	registerUser();
}

void SelectProfilePhoto(lv_event_t * e)
{
    lv_obj_t * dropdown = lv_event_get_target(e);
    uint16_t selected_index = lv_dropdown_get_selected(dropdown);
    
    switch(selected_index) {
        case 0:
            lv_img_set_src(ui_Image30, &ui_img_funina_png);
            break;
        case 1:
            lv_img_set_src(ui_Image30, &ui_img_keqing_png);
            break;
        case 2:
            lv_img_set_src(ui_Image30, &ui_img_linnite_png);
            break;
        case 3:
            lv_img_set_src(ui_Image30, &ui_img_paimen_png);
            break;
        case 4:
            lv_img_set_src(ui_Image30, &ui_img_qiqi_png);
            break;
        default:
            break;
    }
}

/*==========================天气预报界面==============================*/
void ConfirmCheck(lv_event_t * e)
{

	// lv_obj_t * dropdown = lv_event_get_target(e);
	// lv_dropdown_get_selected_str(dropdown, city, sizeof(city));
	if (strlen(city) == 0) {
		strcpy(city, "深圳");
	}
	printf("正在查询%s的天气\n", city);
	getWeather(city);
}

void CheckWeather(lv_event_t * e)
{
	lv_obj_t * dropdown = lv_event_get_target(e);
	lv_dropdown_get_selected_str(dropdown, city, sizeof(city));
	printf("Selected city: %s\n", city);
}



void LEDcontorl(lv_event_t * e)
{
	// Your code here
}

void ChatEvent(lv_event_t * e)
{
	// Your code here
}

void Chat(lv_event_t * e)
{
	// Your code here
}

void SendMessage(lv_event_t * e)
{
	// Your code here
}

void GameStart(lv_event_t * e)
{
	// Your code here
}


