// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void LogIn(lv_event_t * e);
void Register(lv_event_t * e);
void SelectProfilePhoto(lv_event_t * e);
void LEDcontorl(lv_event_t * e);
void ConfirmCheck(lv_event_t * e);
void CheckWeather(lv_event_t * e);
void ChatEvent(lv_event_t * e);
void Chat(lv_event_t * e);
void SendMessage(lv_event_t * e);
void GameStart(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
